### ISSUE TITLE
Invalid deck when adding a card to a deck when no deck exists

### ISSUE THREAD

**Issue by clement-deron** [gumbyscout/fireemblem-cipher-utils#4]
When no deck exists if you try to add a card to a deck it will create a new deck with "invalid_id" as its name but you can't add any card to it. It can be deleted like any other deck though.

platform: windows 10
version: 0.7.0 beta

**Comment by ZaFwamingDwagon** [comment]
Hi @clement-deron . Thank you for contacting us with this issue. I am the tester working with the developer on this so any feedback is appreciated. 

We have identified this as a valid issue and have put it in our queue to address in the future. Please continue to bring up any other questions to us as well, and we hope for your continued support.
