### ISSUE TITLE
Can't install v0.8.0

### ISSUE THREAD

**Issue by BlueHorizon186** [gumbyscout/fireemblem-cipher-utils#7]
Whenever I try to run v0.8.0, Windows says it's a Trojan and deletes the program from my computer :(

**Comment by gumbyscout** [comment]
The application is not a trojan, it's just not signed. Sometimes, virus scanners will have a false positive with executables that aren't signed or are signed with a certificate from a less popular certificate authority. I've actually looked into getting a code signing certificate, but as the application is still in beta, I just haven't felt the need to drop ~$50 on a two year cert just yet. You'll just have to temporarily disable your virus scanner to install it.

**Comment by BlueHorizon186** [comment]
Oh I see! Thank you so much for the clarification. Going to try it again now
